name: CI/CD Pipeline for Project 0.5

# Khi push hoặc pull request vào main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, product, order] # 3 services
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./services/${{ matrix.service }}
        run: npm install

      - name: Run tests
        working-directory: ./services/${{ matrix.service }}
        run: npm test || echo "No test script defined"

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    strategy:
      matrix:
        service: [auth, product, order]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        working-directory: ./services/${{ matrix.service }}
        run: |
          docker build -t your-dockerhub-username/${{ matrix.service }}:latest .
          docker push your-dockerhub-username/${{ matrix.service }}:latest

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            for service in auth product order; do
              docker pull your-dockerhub-username/$service:latest
              docker stop $service || true
              docker rm $service || true
              docker run -d --name $service -p \
                $(case $service in
                  auth) echo 4001;;
                  product) echo 4002;;
                  order) echo 4003;;
                esac):$(case $service in
                  auth) echo 4001;;
                  product) echo 4002;;
                  order) echo 4003;;
                esac) \
                your-dockerhub-username/$service:latest
            done
