name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd auth && npm install
          cd ../product && npm install
          cd ../order && npm install

      - name: Run tests
        run: |
          cd auth && npm test || echo "No test script"
          cd ../product && npm test || echo "No test script"
          cd ../order && npm test || echo "No test script"

      - name: Build Docker images
        run: |
          docker build -t auth ./auth
          docker build -t product ./product
          docker build -t order ./order

      - name: Deploy (local test)
        run: |
          docker stop auth product order || true
          docker rm auth product order || true
          docker run -d --name auth -p 4001:4001 auth
          docker run -d --name product -p 4002:4002 product
          docker run -d --name order -p 4003:4003 order
